import "./globals.css";
import { Nunito } from "next/font/google";
import { Navbar } from "./components/Navbar/Navbar";
import { Modal } from "./components/Modal/Modal";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>
                <Navbar />
                {/* <Modal actionLabel="Submit" title="lorem5" isOpen /> */}
                <div className="antialiased">{children}</div>
            </body>
        </html>
    );
}
